services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: papakopter2137
      MYSQL_DATABASE: signal-sample
      MYSQL_USER: strong-user
      MYSQL_PASSWORD: papakopter2137
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data: